/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of BadRequest
 */
interface BadRequest {
  /** Error code */
  code?: string;
  /** Error desctiption in English */
  message?: string;
}

export class BadRequestError extends ApiError<BadRequest> {}
