/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { ResponseBaseStatusEnum } from '../models/responseBaseStatusEnum';
import {
  ResponseError401AllOf1ErrorsItems,
} from '../models/responseError401AllOf1ErrorsItems';

/**
 * Creates an instance of HTTP401ErrorResponse
 */
interface HTTP401ErrorResponse {
  /** A unique request id in GUID format. The value is written to the Shell API Platform audit log for end to end traceability of a request. */
  RequestId: string;
  /** Indicates overall status of the request */
  Status: ResponseBaseStatusEnum;
  /** Details of error(s) encountered */
  Errors: ResponseError401AllOf1ErrorsItems[];
}

export class HTTP401ErrorResponseError extends ApiError<HTTP401ErrorResponse> {}
