/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { InternalErrorObject } from '../models/internalErrorObject';

/**
 * Creates an instance of InternalServer
 */
interface InternalServer {
  /** requestId is unique identifier value that is attached to requests and messages that allow reference to a particular transaction or event chain. */
  requestId?: string;
  /** Status of the request */
  status?: string;
  /** Exception details of the error */
  errors?: InternalErrorObject[];
  details?: string[];
}

export class InternalServerError extends ApiError<InternalServer> {}
