/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { M400ErrorResponseError } from '../models/m400ErrorResponseError';

/**
 * Creates an instance of M400ErrorResponseError1
 */
interface M400ErrorResponseError1 {
  /** Mandatory UUID (according to RFC 4122 standards) for requests and responses. This will be played back in the response from the request. */
  RequestId: string;
  /** Indicates overall status of the request */
  Status: string;
  Errors?: M400ErrorResponseError[];
}

export class M400ErrorResponseError1Error extends ApiError<M400ErrorResponseError1> {}
