/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { M401ErrorResponseError } from '../models/m401ErrorResponseError';

/**
 * Creates an instance of M401ErrorResponseError1
 */
interface M401ErrorResponseError1 {
  /** Mandatory UUID (according to RFC 4122 standards) for requests and responses. This will be played back in the response from the request. */
  RequestId: string;
  /** Indicates overall status of the request */
  Status: string;
  Errors?: M401ErrorResponseError[];
}

export class M401ErrorResponseError1Error extends ApiError<M401ErrorResponseError1> {}
