/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { M404ErrorResponseError } from '../models/m404ErrorResponseError';

/**
 * Creates an instance of M404ErrorResponseError1
 */
interface M404ErrorResponseError1 {
  /** Mandatory UUID (according to RFC 4122 standards) for requests and responses. This will be played back in the response from the request. */
  RequestId: string;
  /** Indicates overall status of the request */
  Status: string;
  Errors?: M404ErrorResponseError[];
}

export class M404ErrorResponseError1Error extends ApiError<M404ErrorResponseError1> {}
