/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { M405ErrorResponseError } from '../models/m405ErrorResponseError';

/**
 * Creates an instance of M405ErrorResponseError1
 */
interface M405ErrorResponseError1 {
  /** Mandatory UUID (according to RFC 4122 standards) for requests and responses. This will be played back in the response from the request. */
  RequestId: string;
  /** Indicates overall status of the request */
  Status: string;
  Errors?: M405ErrorResponseError[];
}

export class M405ErrorResponseError1Error extends ApiError<M405ErrorResponseError1> {}
