/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { M500ErrorResponseError } from '../models/m500ErrorResponseError';

/**
 * Creates an instance of M500ErrorResponseError1
 */
interface M500ErrorResponseError1 {
  /** Mandatory UUID (according to RFC 4122 standards) for requests and responses. This will be played back in the response from the request. */
  RequestId: string;
  /** Indicates overall status of the request */
  Status: string;
  Errors?: M500ErrorResponseError[];
}

export class M500ErrorResponseError1Error extends ApiError<M500ErrorResponseError1> {}
