/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { UnauthorizedErrMsg } from '../models/unauthorizedErrMsg';

/**
 * Creates an instance of Unauthorized
 */
interface Unauthorized {
  /** requestId or correlation id of the message */
  requestId?: string;
  /** Status of the request */
  status?: string;
  /** Exception details of the error */
  errors?: UnauthorizedErrMsg[];
}

export class UnauthorizedError extends ApiError<Unauthorized> {}
