/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { NotFoundErrMsg } from '../models/notFoundErrMsg.js';

/**
 * Creates an instance of V2ChargeSessionRetrieve404
 */
interface V2ChargeSessionRetrieve404 {
  /** requestId is unique identifier value that is attached to requests and messages that allow reference to a particular transaction or event chain. */
  requestId?: string;
  /** Status of the request */
  status?: string;
  /** Exception details of the error */
  errors?: NotFoundErrMsg[];
}

export class V2ChargeSessionRetrieve404Error extends ApiError<
  V2ChargeSessionRetrieve404
> {}
