/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';
import {
  MultiLocationMarker,
  multiLocationMarkerSchema,
} from '../multiLocationMarker.js';
import {
  SingleLocationMarker,
  singleLocationMarkerSchema,
} from '../singleLocationMarker.js';

/** This is a container type for one-of types. */
export type LocationMarker = SingleLocationMarker | MultiLocationMarker;

const discriminatorMap = {
  'SingleLocation': singleLocationMarkerSchema,
  'MultiLocation': multiLocationMarkerSchema,
};

export const locationMarkerSchema: Schema<LocationMarker> = lazy(() =>
  oneOf(
    [singleLocationMarkerSchema, multiLocationMarkerSchema],
    discriminatorMap,
    'markerType'
  )
);

export namespace LocationMarker {
  /**
   * Validation method to narrow down union type to SingleLocationMarker type case.
   *
   * This is SingleLocationMarker case.
   */
  export function isSingleLocationMarker(
    value: unknown
  ): value is SingleLocationMarker {
    return isMappedValueValidForSchema(value, singleLocationMarkerSchema);
  }

  /**
   * Validation method to narrow down union type to MultiLocationMarker type case.
   *
   * This is MultiLocationMarker case.
   */
  export function isMultiLocationMarker(
    value: unknown
  ): value is MultiLocationMarker {
    return isMappedValueValidForSchema(value, multiLocationMarkerSchema);
  }
}
