/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';
import {
  MultiLocationMarkerV2,
  multiLocationMarkerV2Schema,
} from '../multiLocationMarkerV2.js';
import {
  SingleLocationMarkerV2,
  singleLocationMarkerV2Schema,
} from '../singleLocationMarkerV2.js';

/** This is a container type for one-of types. */
export type LocationMarkerV2 = SingleLocationMarkerV2 | MultiLocationMarkerV2;

const discriminatorMap = {
  'SingleLocation': singleLocationMarkerV2Schema,
  'MultiLocation': multiLocationMarkerV2Schema,
};

export const locationMarkerV2Schema: Schema<LocationMarkerV2> = lazy(() =>
  oneOf(
    [singleLocationMarkerV2Schema, multiLocationMarkerV2Schema],
    discriminatorMap,
    'markerType'
  )
);

export namespace LocationMarkerV2 {
  /**
   * Validation method to narrow down union type to SingleLocationMarkerV2 type case.
   *
   * This is SingleLocationMarkerV2 case.
   */
  export function isSingleLocationMarkerV2(
    value: unknown
  ): value is SingleLocationMarkerV2 {
    return isMappedValueValidForSchema(value, singleLocationMarkerV2Schema);
  }

  /**
   * Validation method to narrow down union type to MultiLocationMarkerV2 type case.
   *
   * This is MultiLocationMarkerV2 case.
   */
  export function isMultiLocationMarkerV2(
    value: unknown
  ): value is MultiLocationMarkerV2 {
    return isMappedValueValidForSchema(value, multiLocationMarkerV2Schema);
  }
}
