/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  AccessibilityStatusEnum,
  accessibilityStatusEnumSchema,
} from './accessibilityStatusEnum';

/** Accessibility of the Location */
export interface Accessibility {
  /** Accessibility Status */
  status?: AccessibilityStatusEnum;
  /** optional Arbitrary text about restrictions of the Location */
  remark?: string;
}

export const accessibilitySchema: Schema<Accessibility> = object({
  status: ['status', optional(accessibilityStatusEnumSchema)],
  remark: ['remark', optional(string())],
});
