/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema.js';
import {
  AccessibilityStatusEnum,
  accessibilityStatusEnumSchema,
} from './accessibilityStatusEnum.js';

/** Accessibility of the Location */
export interface AccessibilityV2 {
  /** Accessibility Status */
  status?: AccessibilityStatusEnum;
}

export const accessibilityV2Schema: Schema<AccessibilityV2> = object({
  status: ['status', optional(accessibilityStatusEnumSchema)],
});
