/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AccessibilityStatusEnum
 */
export enum AccessibilityStatusEnum {
  FreePublic = 'FreePublic',
  PayingPublic = 'PayingPublic',
  Restricted = 'Restricted',
  Unspecified = 'Unspecified',
}

/**
 * Schema for AccessibilityStatusEnum
 */
export const  accessibilityStatusEnumSchema: Schema<AccessibilityStatusEnum> = stringEnum(AccessibilityStatusEnum);
