/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ActiveResponse200JsonStatusEnum
 */
export enum ActiveResponse200JsonStatusEnum {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
}

/**
 * Schema for ActiveResponse200JsonStatusEnum
 */
export const  activeResponse200JsonStatusEnumSchema: Schema<ActiveResponse200JsonStatusEnum> = stringEnum(ActiveResponse200JsonStatusEnum);
