/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  ActiveResponse200JsonStatusEnum,
  activeResponse200JsonStatusEnumSchema,
} from './activeResponse200JsonStatusEnum';
import { DataActive, dataActiveSchema } from './dataActive';

export interface ActiveResponse200Json {
  /** A unique request id in GUID format. The value is written to the Shell API Platform audit log for end to end traceability of a request. */
  requestId: string;
  /** Indicates overall status of the request */
  status: ActiveResponse200JsonStatusEnum;
  data?: DataActive[];
}

export const activeResponse200JsonSchema: Schema<ActiveResponse200Json> = object(
  {
    requestId: ['RequestId', string()],
    status: ['Status', activeResponse200JsonStatusEnumSchema],
    data: ['Data', optional(array(lazy(() => dataActiveSchema)))],
  }
);
