/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ChargeError {
  /** Session code e.g InternalError */
  code?: string;
  /** Session message */
  message?: string;
}

export const chargeErrorSchema: Schema<ChargeError> = object({
  code: ['code', optional(string())],
  message: ['message', optional(string())],
});
