/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ChargesessionStartBody {
  /** Ev charge number */
  evChargeNumber: string;
  /** This is the Electric Vehicle EquipmentID */
  evseId: string;
}

export const chargesessionStartBodySchema: Schema<ChargesessionStartBody> = object(
  { evChargeNumber: ['evChargeNumber', string()], evseId: ['evseId', string()] }
);
