/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ChargesessionStartBody {
  /** The EV Charge Number which can be found on the back of the Shell EV Card */
  evChargeNumber: string;
  /** Standard EVSE (Electric Vehicle Supply Equipment) Id identifier (ISO-IEC-15118) */
  evseId: string;
}

export const chargesessionStartBodySchema: Schema<ChargesessionStartBody> = object(
  { evChargeNumber: ['EvChargeNumber', string()], evseId: ['EvseId', string()] }
);
