/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  ConnectorVOConnectorTypeEnum,
  connectorVOConnectorTypeEnumSchema,
} from './connectorVOConnectorTypeEnum.js';
import {
  ElectricalPropertiesV2,
  electricalPropertiesV2Schema,
} from './electricalPropertiesV2.js';

/** An EVSE can have one or many Connectors. Each Connector will normally have a different socket / cable and only one can be used to charge at a time. */
export interface ConnectorV2 {
  /** Internal identifier used to refer to this Connector */
  uid?: string;
  /** Identifier of the Evse as given by the Operator, unique for the containing EVSE' */
  externalId?: string;
  /** Type of the connector in the EVSE unit. */
  connectorType?: ConnectorVOConnectorTypeEnum;
  /** Electrical Properties of the Connector */
  electricalProperties?: ElectricalPropertiesV2;
}

export const connectorV2Schema: Schema<ConnectorV2> = lazy(() =>
  object({
    uid: ['uid', optional(string())],
    externalId: ['externalId', optional(string())],
    connectorType: [
      'connectorType',
      optional(connectorVOConnectorTypeEnumSchema),
    ],
    electricalProperties: [
      'electricalProperties',
      optional(electricalPropertiesV2Schema),
    ],
  })
);
