/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ConnectorVOUpdatedByEnum
 */
export enum ConnectorVOUpdatedByEnum {
  Feed = 'Feed',
  Admin = 'Admin',
  TariffService = 'TariffService',
  Defaults = 'Defaults',
}

/**
 * Schema for ConnectorVOUpdatedByEnum
 */
export const connectorVOUpdatedByEnumSchema: Schema<ConnectorVOUpdatedByEnum> = stringEnum(
  ConnectorVOUpdatedByEnum
);
