/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ConnectorVOConnectorTypeEnum
 */
export enum ConnectorVOConnectorTypeEnum {
  Avcon = 'Avcon',
  Domestic = 'Domestic',
  Industrial2PDc = 'Industrial2PDc',
  IndustrialPneAc = 'IndustrialPneAc',
  Industrial3PEAc = 'Industrial3PEAc',
  Industrial3PENAc = 'Industrial3PENAc',
  Type1 = 'Type1',
  Type1Combo = 'Type1Combo',
  Type2 = 'Type2',
  Type2Combo = 'Type2Combo',
  Type3 = 'Type3',
  LPI = 'LPI',
  Nema520 = 'Nema520',
  SAEJ1772 = 'SAEJ1772',
  SPI = 'SPI',
  TepcoCHAdeMO = 'TepcoCHAdeMO',
  Tesla = 'Tesla',
  Unspecified = 'Unspecified',
}

/**
 * Schema for ConnectorVOConnectorTypeEnum
 */
export const  connectorVOConnectorTypeEnumSchema: Schema<ConnectorVOConnectorTypeEnum> = stringEnum(ConnectorVOConnectorTypeEnum);
