/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema.js';

export interface Coordinates1 {
  /** Latitude of the Coordinate */
  latitude?: number;
  /** Longitude of the Coordinate */
  longitude?: number;
}

export const coordinates1Schema: Schema<Coordinates1> = object({
  latitude: ['latitude', optional(number())],
  longitude: ['longitude', optional(number())],
});
