/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DataRetrieveSessionCodeEnum
 */
export enum DataRetrieveSessionCodeEnum {
  InternalError = 'InternalError',
  ServiceUnavailable = 'ServiceUnavailable',
  ChargeTokenNotSupported = 'ChargeTokenNotSupported',
  SessionInvalid = 'SessionInvalid',
  EvNotConnectedToEvse = 'EvNotConnectedToEvse',
  EvseInUse = 'EvseInUse',
  EvseOutOfService = 'EvseOutOfService',
  EvseNotFound = 'EvseNotFound',
  EvseNotSupported = 'EvseNotSupported',
}

/**
 * Schema for DataRetrieveSessionCodeEnum
 */
export const  dataRetrieveSessionCodeEnumSchema: Schema<DataRetrieveSessionCodeEnum> = stringEnum(DataRetrieveSessionCodeEnum);
