/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DataActiveSessionCodeEnum
 */
export enum DataActiveSessionCodeEnum {
  InternalError = 'InternalError',
  ServiceUnavailable = 'ServiceUnavailable',
  ChargeTokenNotSupported = 'ChargeTokenNotSupported',
  SessionInvalid = 'SessionInvalid',
  EvNotConnectedToEvse = 'EvNotConnectedToEvse',
  EvseInUse = 'EvseInUse',
  EvseOutOfService = 'EvseOutOfService',
  EvseNotFound = 'EvseNotFound',
  EvseNotSupported = 'EvseNotSupported',
}

/**
 * Schema for DataActiveSessionCodeEnum
 */
export const  dataActiveSessionCodeEnumSchema: Schema<DataActiveSessionCodeEnum> = stringEnum(DataActiveSessionCodeEnum);
