/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';
import {
  DataRetrieveSessionCodeEnum,
  dataRetrieveSessionCodeEnumSchema,
} from './dataRetrieveSessionCodeEnum';
import {
  DataRetrieveSessionStateEnum,
  dataRetrieveSessionStateEnumSchema,
} from './dataRetrieveSessionStateEnum';

export interface DataRetrieve {
  /** Id of the session */
  id?: string;
  /** Id of the user that started the session */
  userId?: string;
  /** Id of the evse that the user is charging */
  emaId?: string;
  /** Ema-id of the charge token that is used */
  evseId?: string;
  /** When the session is started */
  startedAt?: string;
  /** When the session is stopped */
  stoppedAt?: string | null;
  /** Describes the session state */
  sessionState?: DataRetrieveSessionStateEnum;
  /** Session code e.g InternalError */
  sessionCode?: DataRetrieveSessionCodeEnum | null;
  /** Session message */
  sessionMessage?: string | null;
}

export const dataRetrieveSchema: Schema<DataRetrieve> = object({
  id: ['Id', optional(string())],
  userId: ['UserId', optional(string())],
  emaId: ['EmaId', optional(string())],
  evseId: ['EvseId', optional(string())],
  startedAt: ['StartedAt', optional(string())],
  stoppedAt: ['StoppedAt', optional(nullable(string()))],
  sessionState: ['SessionState', optional(dataRetrieveSessionStateEnumSchema)],
  sessionCode: [
    'SessionCode',
    optional(nullable(dataRetrieveSessionCodeEnumSchema)),
  ],
  sessionMessage: ['SessionMessage', optional(nullable(string()))],
});
