/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ElectricalPropertiesPowerTypeEnum
 */
export enum ElectricalPropertiesPowerTypeEnum {
  AC1Phase = 'AC1Phase',
  AC3Phase = 'AC3Phase',
  DC = 'DC',
}

/**
 * Schema for ElectricalPropertiesPowerTypeEnum
 */
export const electricalPropertiesPowerTypeEnumSchema: Schema<ElectricalPropertiesPowerTypeEnum> = stringEnum(
  ElectricalPropertiesPowerTypeEnum
);
