/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema.js';
import {
  ElectricalPropertiesPowerTypeEnum,
  electricalPropertiesPowerTypeEnumSchema,
} from './electricalPropertiesPowerTypeEnum.js';

/** Electrical Properties of the Connector */
export interface ElectricalPropertiesV2 {
  /** Power Type used in this connector. */
  powerType?: ElectricalPropertiesPowerTypeEnum;
  /** Voltage in Volts for this connector */
  voltage?: number;
  /** Electric Current in Amperes for this connector */
  amperage?: number;
  /** Power in Kilowatts for this connector */
  maxElectricPower?: number;
}

export const electricalPropertiesV2Schema: Schema<ElectricalPropertiesV2> = object(
  {
    powerType: ['powerType', optional(electricalPropertiesPowerTypeEnumSchema)],
    voltage: ['voltage', optional(number())],
    amperage: ['amperage', optional(number())],
    maxElectricPower: ['maxElectricPower', optional(number())],
  }
);
