/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for EvseStatusEnum
 */
export enum EvseStatusEnum {
  Available = 'Available',
  Occupied = 'Occupied',
  Unavailable = 'Unavailable',
  Unknown = 'Unknown',
}

/**
 * Schema for EvseStatusEnum
 */
export const evseStatusEnumSchema: Schema<EvseStatusEnum> = stringEnum(
  EvseStatusEnum
);
