/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for EvseVOAuthorizationMethodsEnum
 */
export enum EvseVOAuthorizationMethodsEnum {
  NewMotionApp = 'NewMotionApp',
  RFIDToken = 'RFIDToken',
  PnC = 'PnC',
}

/**
 * Schema for EvseVOAuthorizationMethodsEnum
 */
export const  evseVOAuthorizationMethodsEnumSchema: Schema<EvseVOAuthorizationMethodsEnum> = stringEnum(EvseVOAuthorizationMethodsEnum);
