/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for EvseVOStatusEnum
 */
export enum EvseVOStatusEnum {
  Available = 'Available',
  Occupied = 'Occupied',
  Unavailable = 'Unavailable',
  Unknown = 'Unknown',
}

/**
 * Schema for EvseVOStatusEnum
 */
export const evseVOStatusEnumSchema: Schema<EvseVOStatusEnum> = stringEnum(
  EvseVOStatusEnum
);
