/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { DataRetrieve, dataRetrieveSchema } from './dataRetrieve.js';
import {
  GetChargeSessionRetrieveResponse200JsonStatusEnum,
  getChargeSessionRetrieveResponse200JsonStatusEnumSchema,
} from './getChargeSessionRetrieveResponse200JsonStatusEnum.js';

export interface GetChargeSessionRetrieveResponse200Json {
  /** Mandatory UUID (according to RFC 4122 standards) for requests and responses. This will be played back in the response from the request. */
  requestId: string;
  status: GetChargeSessionRetrieveResponse200JsonStatusEnum;
  data?: DataRetrieve[];
}

export const getChargeSessionRetrieveResponse200JsonSchema: Schema<GetChargeSessionRetrieveResponse200Json> = lazy(
  () =>
    object({
      requestId: ['requestId', string()],
      status: [
        'status',
        getChargeSessionRetrieveResponse200JsonStatusEnumSchema,
      ],
      data: ['data', optional(array(dataRetrieveSchema))],
    })
);
