/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for GetChargeSessionRetrieveResponse200JsonStatusEnum
 */
export enum GetChargeSessionRetrieveResponse200JsonStatusEnum {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
}

/**
 * Schema for GetChargeSessionRetrieveResponse200JsonStatusEnum
 */
export const  getChargeSessionRetrieveResponse200JsonStatusEnumSchema: Schema<GetChargeSessionRetrieveResponse200JsonStatusEnum> = stringEnum(GetChargeSessionRetrieveResponse200JsonStatusEnum);
