/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { DataRetrieve, dataRetrieveSchema } from './dataRetrieve';
import {
  GetChargeSessionRetrieveResponse200JsonStatusEnum,
  getChargeSessionRetrieveResponse200JsonStatusEnumSchema,
} from './getChargeSessionRetrieveResponse200JsonStatusEnum';

export interface GetChargeSessionRetrieveResponse200Json {
  /** A unique request id in GUID format. The value is written to the Shell API Platform audit log for end to end traceability of a request. */
  requestId: string;
  /** Indicates overall status of the request */
  status: GetChargeSessionRetrieveResponse200JsonStatusEnum;
  data?: DataRetrieve[];
}

export const getChargeSessionRetrieveResponse200JsonSchema: Schema<GetChargeSessionRetrieveResponse200Json> = object(
  {
    requestId: ['RequestId', string()],
    status: ['Status', getChargeSessionRetrieveResponse200JsonStatusEnumSchema],
    data: ['Data', optional(array(lazy(() => dataRetrieveSchema)))],
  }
);
