/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for GetEVLocationsAuthorizationMethodsEnum
 */
export enum GetEVLocationsAuthorizationMethodsEnum {
  NewMotionApp = 'NewMotionApp',
  RFIDToken = 'RFIDToken',
  PnC = 'PnC',
}

/**
 * Schema for GetEVLocationsAuthorizationMethodsEnum
 */
export const getEVLocationsAuthorizationMethodsEnumSchema: Schema<GetEVLocationsAuthorizationMethodsEnum> = stringEnum(
  GetEVLocationsAuthorizationMethodsEnum
);
