/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for GetLocationsListAuthorizationMethodsEnum
 */
export enum GetLocationsListAuthorizationMethodsEnum {
  NewMotionApp = 'NewMotionApp',
  RFIDToken = 'RFIDToken',
  PnC = 'PnC',
}

/**
 * Schema for GetLocationsListAuthorizationMethodsEnum
 */
export const  getLocationsListAuthorizationMethodsEnumSchema: Schema<GetLocationsListAuthorizationMethodsEnum> = stringEnum(GetLocationsListAuthorizationMethodsEnum);
