/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for GetLocationsListEvseStatusEnum
 */
export enum GetLocationsListEvseStatusEnum {
  Available = 'Available',
  Occupied = 'Occupied',
  Unavailable = 'Unavailable',
  Unknown = 'Unknown',
}

/**
 * Schema for GetLocationsListEvseStatusEnum
 */
export const  getLocationsListEvseStatusEnumSchema: Schema<GetLocationsListEvseStatusEnum> = stringEnum(GetLocationsListEvseStatusEnum);
