/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for GetMarkersListEvseStatusEnum
 */
export enum GetMarkersListEvseStatusEnum {
  Available = 'Available',
  Occupied = 'Occupied',
  Unavailable = 'Unavailable',
  Unknown = 'Unknown',
}

/**
 * Schema for GetMarkersListEvseStatusEnum
 */
export const  getMarkersListEvseStatusEnumSchema: Schema<GetMarkersListEvseStatusEnum> = stringEnum(GetMarkersListEvseStatusEnum);
