/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for GetMarkersListAuthorizationMethodsEnum
 */
export enum GetMarkersListAuthorizationMethodsEnum {
  NewMotionApp = 'NewMotionApp',
  RFIDToken = 'RFIDToken',
  PnC = 'PnC',
}

/**
 * Schema for GetMarkersListAuthorizationMethodsEnum
 */
export const  getMarkersListAuthorizationMethodsEnumSchema: Schema<GetMarkersListAuthorizationMethodsEnum> = stringEnum(GetMarkersListAuthorizationMethodsEnum);
