/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for GetNearbyLocationsEvseStatusEnum
 */
export enum GetNearbyLocationsEvseStatusEnum {
  Available = 'Available',
  Occupied = 'Occupied',
  Unavailable = 'Unavailable',
  Unknown = 'Unknown',
}

/**
 * Schema for GetNearbyLocationsEvseStatusEnum
 */
export const  getNearbyLocationsEvseStatusEnumSchema: Schema<GetNearbyLocationsEvseStatusEnum> = stringEnum(GetNearbyLocationsEvseStatusEnum);
