/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for GetNearbyLocationsAuthorizationMethodsEnum
 */
export enum GetNearbyLocationsAuthorizationMethodsEnum {
  NewMotionApp = 'NewMotionApp',
  RFIDToken = 'RFIDToken',
  PnC = 'PnC',
}

/**
 * Schema for GetNearbyLocationsAuthorizationMethodsEnum
 */
export const  getNearbyLocationsAuthorizationMethodsEnumSchema: Schema<GetNearbyLocationsAuthorizationMethodsEnum> = stringEnum(GetNearbyLocationsAuthorizationMethodsEnum);
