/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InlineResponse2021StatusEnum
 */
export enum InlineResponse2021StatusEnum {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
}

/**
 * Schema for InlineResponse2021StatusEnum
 */
export const inlineResponse2021StatusEnumSchema: Schema<InlineResponse2021StatusEnum> = stringEnum(
  InlineResponse2021StatusEnum
);
