/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import {
  InlineResponse202Data,
  inlineResponse202DataSchema,
} from './inlineResponse202Data';
import {
  InlineResponse202StatusEnum,
  inlineResponse202StatusEnumSchema,
} from './inlineResponse202StatusEnum';

export interface InlineResponse202 {
  /** Mandatory UUID (according to RFC 4122 standards) for requests and responses. This will be played back in the response from the request. */
  requestId: string;
  /** Indicates overall status of the request */
  status: InlineResponse202StatusEnum;
  data: InlineResponse202Data[];
}

export const inlineResponse202Schema: Schema<InlineResponse202> = object({
  requestId: ['RequestId', string()],
  status: ['Status', inlineResponse202StatusEnumSchema],
  data: ['Data', array(lazy(() => inlineResponse202DataSchema))],
});
