/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InlineResponse202StatusEnum
 */
export enum InlineResponse202StatusEnum {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
}

/**
 * Schema for InlineResponse202StatusEnum
 */
export const inlineResponse202StatusEnumSchema: Schema<InlineResponse202StatusEnum> = stringEnum(
  InlineResponse202StatusEnum
);
