/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface InlineResponse202Data {
  /** Session Id for tracking. */
  sessionId?: string;
}

export const inlineResponse202DataSchema: Schema<InlineResponse202Data> = object(
  { sessionId: ['sessionId', optional(string())] }
);
