/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface InternalErrorObject {
  /** Error code */
  code?: string;
  /** Error description in English */
  message?: string;
  /** Technical details of the error message, the example which is given in the sample payload is one of the scenario. actual response will vary based on the technical nature */
  description?: string;
}

export const internalErrorObjectSchema: Schema<InternalErrorObject> = object({
  code: ['code', optional(string())],
  message: ['message', optional(string())],
  description: ['description', optional(string())],
});
