/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for LocationsMarkersAuthorizationMethodsEnum
 */
export enum LocationsMarkersAuthorizationMethodsEnum {
  NewMotionApp = 'NewMotionApp',
  RFIDToken = 'RFIDToken',
  PnC = 'PnC',
}

/**
 * Schema for LocationsMarkersAuthorizationMethodsEnum
 */
export const locationsMarkersAuthorizationMethodsEnumSchema: Schema<LocationsMarkersAuthorizationMethodsEnum> = stringEnum(
  LocationsMarkersAuthorizationMethodsEnum
);
