/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  M401ErrorResponseError,
  m401ErrorResponseErrorSchema,
} from './m401ErrorResponseError';

/** Unauthorized */
export interface M401ErrorResponse {
  /** Mandatory UUID (according to RFC 4122 standards) for requests and responses. This will be played back in the response from the request. */
  requestId: string;
  /** Indicates overall status of the request */
  status: string;
  errors?: M401ErrorResponseError[];
}

export const m401ErrorResponseSchema: Schema<M401ErrorResponse> = object({
  requestId: ['RequestId', string()],
  status: ['Status', string()],
  errors: ['Errors', optional(array(lazy(() => m401ErrorResponseErrorSchema)))],
});
