/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  M404ErrorResponseError,
  m404ErrorResponseErrorSchema,
} from './m404ErrorResponseError';

/**
 * Invalid charge token with given EmaId was not found.
 * Backend HTTP 410 should be transformed to 404.
 */
export interface M404ErrorResponse {
  /** Mandatory UUID (according to RFC 4122 standards) for requests and responses. This will be played back in the response from the request. */
  requestId: string;
  /** Indicates overall status of the request */
  status: string;
  errors?: M404ErrorResponseError[];
}

export const m404ErrorResponseSchema: Schema<M404ErrorResponse> = object({
  requestId: ['RequestId', string()],
  status: ['Status', string()],
  errors: ['Errors', optional(array(lazy(() => m404ErrorResponseErrorSchema)))],
});
