/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  M405ErrorResponseError,
  m405ErrorResponseErrorSchema,
} from './m405ErrorResponseError';

/** Method Not Allowed */
export interface M405ErrorResponse {
  /** Mandatory UUID (according to RFC 4122 standards) for requests and responses. This will be played back in the response from the request. */
  requestId: string;
  /** Indicates overall status of the request */
  status: string;
  errors?: M405ErrorResponseError[];
}

export const m405ErrorResponseSchema: Schema<M405ErrorResponse> = object({
  requestId: ['RequestId', string()],
  status: ['Status', string()],
  errors: ['Errors', optional(array(lazy(() => m405ErrorResponseErrorSchema)))],
});
