/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  M429ErrorResponseError,
  m429ErrorResponseErrorSchema,
} from './m429ErrorResponseError';

/** Too Many Requests */
export interface M429ErrorResponse {
  /** Mandatory UUID (according to RFC 4122 standards) for requests and responses. This will be played back in the response from the request. */
  requestId: string;
  /** Indicates overall status of the request */
  status: string;
  errors?: M429ErrorResponseError[];
}

export const m429ErrorResponseSchema: Schema<M429ErrorResponse> = object({
  requestId: ['RequestId', string()],
  status: ['Status', string()],
  errors: ['Errors', optional(array(lazy(() => m429ErrorResponseErrorSchema)))],
});
