/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, nullable, object, optional, Schema, string } from '../schema';

export interface M500ErrorResponseError {
  /** Error code that logically best represents the error encountered */
  code: string;
  /** Description of the error type */
  title: string;
  /** Details of the error that can help under the cause of the error */
  detail: string;
  additionalInfo?: Record<string, string | null> | null;
}

export const m500ErrorResponseErrorSchema: Schema<M500ErrorResponseError> = object(
  {
    code: ['Code', string()],
    title: ['Title', string()],
    detail: ['Detail', string()],
    additionalInfo: [
      'AdditionalInfo',
      optional(nullable(dict(nullable(string())))),
    ],
  }
);
