/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema.js';
import { Coordinates, coordinatesSchema } from './coordinates.js';

/** A Marker is a place on the map that represent multiple Locations at the same spot */
export interface MultiLocationMarkerV2 {
  /** Coordinates of the Shell Recharge Site Location */
  coordinates?: Coordinates;
  /** Number of Locations that this Marker represents in the given set of bounds */
  locationCount?: number;
  /** Total number of Evses in Locations that this Marker represents */
  evseCount?: number;
  /** Maximum power in kW across all locations grouped in this marker (disregarding availability) */
  maxPower?: number;
  /** Operator of this Shell Recharge Location */
  operatorName?: string;
  /** Type of the Marker, in this case it will always be MultiLocation */
  markerType: string;
}

export const multiLocationMarkerV2Schema: Schema<MultiLocationMarkerV2> = lazy(
  () =>
    object({
      coordinates: ['coordinates', optional(coordinatesSchema)],
      locationCount: ['locationCount', optional(number())],
      evseCount: ['evseCount', optional(number())],
      maxPower: ['maxPower', optional(number())],
      operatorName: ['operatorName', optional(string())],
      markerType: ['markerType', string()],
    })
);
