/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for NearbyLocationsAuthorizationMethodsEnum
 */
export enum NearbyLocationsAuthorizationMethodsEnum {
  NewMotionApp = 'NewMotionApp',
  RFIDToken = 'RFIDToken',
  PnC = 'PnC',
}

/**
 * Schema for NearbyLocationsAuthorizationMethodsEnum
 */
export const nearbyLocationsAuthorizationMethodsEnumSchema: Schema<NearbyLocationsAuthorizationMethodsEnum> = stringEnum(
  NearbyLocationsAuthorizationMethodsEnum
);
