/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OpeningHoursObjectWeekDayEnum
 */
export enum OpeningHoursObjectWeekDayEnum {
  Sun = 'Sun',
  Mon = 'Mon',
  Tue = 'Tue',
  Wed = 'Wed',
  Thu = 'Thu',
  Fri = 'Fri',
  Sat = 'Sat',
}

/**
 * Schema for OpeningHoursObjectWeekDayEnum
 */
export const  openingHoursObjectWeekDayEnumSchema: Schema<OpeningHoursObjectWeekDayEnum> = stringEnum(OpeningHoursObjectWeekDayEnum);
