/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  OpeningHoursObjectWeekDayEnum,
  openingHoursObjectWeekDayEnumSchema,
} from './openingHoursObjectWeekDayEnum';

export interface OpeningHoursObject {
  /** 3 letter day of the week */
  weekDay?: OpeningHoursObjectWeekDayEnum;
  /** Hour in 24h local time when the location opens. */
  startTime?: string;
  /** Hour in 24h local time when the location closes. */
  endTime?: string;
}

export const openingHoursObjectSchema: Schema<OpeningHoursObject> = object({
  weekDay: ['weekDay', optional(openingHoursObjectWeekDayEnumSchema)],
  startTime: ['startTime', optional(string())],
  endTime: ['endTime', optional(string())],
});
