/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema.js';

export interface PowerRange {
  /** Minimum supported power in kW */
  min: number;
  /** Maximum supported power in kW */
  max: number;
}

export const powerRangeSchema: Schema<PowerRange> = object({
  min: ['min', number()],
  max: ['max', number()],
});
