/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema.js';
import { TypeEnum, typeEnumSchema } from './typeEnum.js';

export interface PriceComponent {
  /** Type of the price component */
  type: TypeEnum;
  /** Step size in seconds for TIME-based components, in kWh for ENERGY-based components, or 1 for FLAT components */
  stepSize: number;
  /** Price per step in the specified currency for this price component */
  price: number;
  /** VAT percentage applicable to this price component */
  vat: number;
}

export const priceComponentSchema: Schema<PriceComponent> = object({
  type: ['type', typeEnumSchema],
  stepSize: ['stepSize', number()],
  price: ['price', number()],
  vat: ['vat', number()],
});
