/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import {
  LocationResponeObjectV2,
  locationResponeObjectV2Schema,
} from './locationResponeObjectV2.js';

export interface ResponseV2 {
  /** requestId is unique identifier value that is attached to requests and messages that allow reference to a particular transaction or event chain. */
  requestId?: string;
  /** status of the API call */
  status?: string;
  /** API Response */
  data?: LocationResponeObjectV2[];
}

export const responseV2Schema: Schema<ResponseV2> = lazy(() =>
  object({
    requestId: ['requestId', optional(string())],
    status: ['status', optional(string())],
    data: ['data', optional(array(locationResponeObjectV2Schema))],
  })
);
