/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import {
  ResponseError401AllOf1ErrorsItems,
  responseError401AllOf1ErrorsItemsSchema,
} from './responseError401AllOf1ErrorsItems';

export interface ResponseError401AllOf1 {
  /** Details of error(s) encountered */
  errors: ResponseError401AllOf1ErrorsItems[];
}

export const responseError401AllOf1Schema: Schema<ResponseError401AllOf1> = object(
  {
    errors: [
      'Errors',
      array(lazy(() => responseError401AllOf1ErrorsItemsSchema)),
    ],
  }
);
