/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ResponseBaseStatusEnum
 */
export enum ResponseBaseStatusEnum {
  FAILED = 'FAILED',
  PARTIALSUCCESS = 'PARTIAL_SUCCESS',
  SUCCESS = 'SUCCESS',
}

/**
 * Schema for ResponseBaseStatusEnum
 */
export const  responseBaseStatusEnumSchema: Schema<ResponseBaseStatusEnum> = stringEnum(ResponseBaseStatusEnum);
