/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, optional, Schema, string } from '../schema.js';
import { DayOfWeekEnum, dayOfWeekEnumSchema } from './dayOfWeekEnum.js';

export interface Restrictions {
  /** Valid from this time of the day (HH:mm) */
  startTime?: string;
  /** Valid until this time of the day (HH:mm) */
  endTime?: string;
  startDate?: string;
  endDate?: string;
  minKwh?: number;
  maxKwh?: number;
  minCurrent?: number;
  maxCurrent?: number;
  minPower?: number;
  maxPower?: number;
  /** Minimum session duration in seconds */
  minDuration?: number;
  /** Maximum session duration in seconds */
  maxDuration?: number;
  dayOfWeek?: DayOfWeekEnum[];
}

export const restrictionsSchema: Schema<Restrictions> = object({
  startTime: ['startTime', optional(string())],
  endTime: ['endTime', optional(string())],
  startDate: ['startDate', optional(string())],
  endDate: ['endDate', optional(string())],
  minKwh: ['minKwh', optional(number())],
  maxKwh: ['maxKwh', optional(number())],
  minCurrent: ['minCurrent', optional(number())],
  maxCurrent: ['maxCurrent', optional(number())],
  minPower: ['minPower', optional(number())],
  maxPower: ['maxPower', optional(number())],
  minDuration: ['minDuration', optional(number())],
  maxDuration: ['maxDuration', optional(number())],
  dayOfWeek: ['dayOfWeek', optional(array(dayOfWeekEnumSchema))],
});
