/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { AccessibilityV2, accessibilityV2Schema } from './accessibilityV2.js';
import { Address, addressSchema } from './address.js';
import { Coordinates, coordinatesSchema } from './coordinates.js';
import {
  OpeningHoursObject,
  openingHoursObjectSchema,
} from './openingHoursObject.js';
import { SearchByIdEvse, searchByIdEvseSchema } from './searchByIdEvse.js';

export interface SearchByIdLocationRespone {
  /** Unique Internal identifier used to refer to this Location by Shell Recharge */
  uid?: string;
  /** Identifier as given by the Shell Recharge Operator, unique for that Operator */
  externalId?: string;
  /** Coordinates of the Shell Recharge Site Location */
  coordinates?: Coordinates;
  /** Operator of this Shell Recharge Location */
  operatorName?: string;
  /** Address of the Shell Recharge Location */
  address?: Address;
  /** Accessibility of the Location */
  accessibility?: AccessibilityV2;
  evses?: SearchByIdEvse[];
  /** Optional Opening Hours of the Location. Please note that it is not available for all sites. */
  openingHours?: OpeningHoursObject[];
  /** ISO8601-compliant UTC datetime of the last update of the location */
  updated?: string;
  /** the type of the location. Could be "UNKNOWN". */
  locationType?: string;
  /** Unique Id of the operator */
  operatorId?: string;
  /** Whether the location is open 24/7 */
  openTwentyFourSeven?: boolean;
}

export const searchByIdLocationResponeSchema: Schema<SearchByIdLocationRespone> = lazy(
  () =>
    object({
      uid: ['uid', optional(string())],
      externalId: ['externalId', optional(string())],
      coordinates: ['coordinates', optional(coordinatesSchema)],
      operatorName: ['operatorName', optional(string())],
      address: ['address', optional(addressSchema)],
      accessibility: ['accessibility', optional(accessibilityV2Schema)],
      evses: ['evses', optional(array(searchByIdEvseSchema))],
      openingHours: ['openingHours', optional(array(openingHoursObjectSchema))],
      updated: ['updated', optional(string())],
      locationType: ['locationType', optional(string())],
      operatorId: ['operatorId', optional(string())],
      openTwentyFourSeven: ['openTwentyFourSeven', optional(boolean())],
    })
);
