/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import {
  EvseVOStatusEnum,
  evseVOStatusEnumSchema,
} from './evseVOStatusEnum.js';
import {
  SearchByIdConnector,
  searchByIdConnectorSchema,
} from './searchByIdConnector.js';
import {
  SingleLocationMarkerAuthorizationMethodsItemsEnum,
  singleLocationMarkerAuthorizationMethodsItemsEnumSchema,
} from './singleLocationMarkerAuthorizationMethodsItemsEnum.js';

/** Each Location will contain one or more EVSEs (Electric Vehicle Supply Equipment). Each EVSE is capable of charging one car at a time. */
export interface SearchByIdEvse {
  /** Internal identifier used to refer to single individual  EVSE unit. */
  uid?: string;
  /** Identifier of the Evse as given by the Operator, unique for that Operator */
  externalId?: string;
  /** Standard EVSEId identifier (ISO-IEC-15118) */
  evseId?: string;
  /** The current status of the EVSE units availability */
  status?: EvseVOStatusEnum;
  /** ISO8601-compliant UTC datetime of the last update of the EVSE */
  updated?: string;
  /** An optional number/string printed on the outside of the EVSE for visual identification */
  physicalReference?: string;
  /** List of all connectors available on this EVSE unit. */
  connectors?: SearchByIdConnector[];
  /** Methods that can be used to Authorize sessions on this EVSE */
  authorizationMethods?: SingleLocationMarkerAuthorizationMethodsItemsEnum[];
}

export const searchByIdEvseSchema: Schema<SearchByIdEvse> = lazy(() =>
  object({
    uid: ['uid', optional(string())],
    externalId: ['externalId', optional(string())],
    evseId: ['evseId', optional(string())],
    status: ['status', optional(evseVOStatusEnumSchema)],
    updated: ['updated', optional(string())],
    physicalReference: ['physicalReference', optional(string())],
    connectors: ['connectors', optional(array(searchByIdConnectorSchema))],
    authorizationMethods: [
      'authorizationMethods',
      optional(array(singleLocationMarkerAuthorizationMethodsItemsEnumSchema)),
    ],
  })
);
