/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import {
  SearchByIdLocationRespone,
  searchByIdLocationResponeSchema,
} from './searchByIdLocationRespone.js';

export interface SearchByIdResponse {
  /** requestId is unique identifier value that is attached to requests and messages that allow reference to a particular transaction or event chain. */
  requestId?: string;
  /** status of the API call */
  status?: string;
  /** API Response */
  data?: SearchByIdLocationRespone[];
}

export const searchByIdResponseSchema: Schema<SearchByIdResponse> = lazy(() =>
  object({
    requestId: ['requestId', optional(string())],
    status: ['status', optional(string())],
    data: ['data', optional(array(searchByIdLocationResponeSchema))],
  })
);
