/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import {
  LocationMarker,
  locationMarkerSchema,
} from './containers/locationMarker.js';

export interface SingleLocationMarkerResponse {
  /** requestId is unique identifier value that is attached to requests and messages that allow reference to a particular transaction or event chain. */
  requestId?: string;
  /** status of the API call */
  status?: string;
  data?: LocationMarker[];
}

export const singleLocationMarkerResponseSchema: Schema<SingleLocationMarkerResponse> = lazy(
  () =>
    object({
      requestId: ['requestId', optional(string())],
      status: ['status', optional(string())],
      data: ['data', optional(array(locationMarkerSchema))],
    })
);
