/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SingleLocationMarkerAuthorizationMethodsItemsEnum
 */
export enum SingleLocationMarkerAuthorizationMethodsItemsEnum {
  NewMotionApp = 'NewMotionApp',
  RFIDToken = 'RFIDToken',
  PnC = 'PnC',
}

/**
 * Schema for SingleLocationMarkerAuthorizationMethodsItemsEnum
 */
export const  singleLocationMarkerAuthorizationMethodsItemsEnumSchema: Schema<SingleLocationMarkerAuthorizationMethodsItemsEnum> = stringEnum(SingleLocationMarkerAuthorizationMethodsItemsEnum);
