/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { Coordinates, coordinatesSchema } from './coordinates.js';
import {
  SingleLocationMarkerAuthorizationMethodsItemsEnum,
  singleLocationMarkerAuthorizationMethodsItemsEnumSchema,
} from './singleLocationMarkerAuthorizationMethodsItemsEnum.js';
import {
  SingleLocationMarkerStatusEnum,
  singleLocationMarkerStatusEnumSchema,
} from './singleLocationMarkerStatusEnum.js';

/** A Marker is a place on the map that represent a single Location */
export interface SingleLocationMarkerV2 {
  /** Minimum of all status values in the Marker, e.g. if at least one Evse in the Marker is available, the value will be available */
  status?: SingleLocationMarkerStatusEnum;
  /** Coordinates of the Shell Recharge Site Location */
  coordinates?: Coordinates;
  /** Total number of Evse units in Locations that this Marker represents */
  evseCount?: number;
  /** Maximum power in kW across all locations grouped in this marker (disregarding availability) */
  maxPower?: number;
  /** Number of Locations that this Marker represents in the given set of bounds */
  locationCount?: number;
  /** Unique ID of the Location this Marker represents */
  locationUid?: string;
  /** Methods that can be used to Authorize sessions on this EVSE */
  authorizationMethods?: SingleLocationMarkerAuthorizationMethodsItemsEnum[];
  /** Operator of this Shell Recharge Location */
  operatorName?: string;
  /** Type of the Marker, in this case it will always be SingleLocation */
  markerType: string;
}

export const singleLocationMarkerV2Schema: Schema<SingleLocationMarkerV2> = lazy(
  () =>
    object({
      status: ['status', optional(singleLocationMarkerStatusEnumSchema)],
      coordinates: ['coordinates', optional(coordinatesSchema)],
      evseCount: ['evseCount', optional(number())],
      maxPower: ['maxPower', optional(number())],
      locationCount: ['locationCount', optional(number())],
      locationUid: ['locationUid', optional(string())],
      authorizationMethods: [
        'authorizationMethods',
        optional(
          array(singleLocationMarkerAuthorizationMethodsItemsEnumSchema)
        ),
      ],
      operatorName: ['operatorName', optional(string())],
      markerType: ['markerType', string()],
    })
);
