/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SingleLocationMarkerStatusEnum
 */
export enum SingleLocationMarkerStatusEnum {
  Available = 'Available',
  Occupied = 'Occupied',
  Unavailable = 'Unavailable',
  Unknown = 'Unknown',
}

/**
 * Schema for SingleLocationMarkerStatusEnum
 */
export const singleLocationMarkerStatusEnumSchema: Schema<SingleLocationMarkerStatusEnum> = stringEnum(
  SingleLocationMarkerStatusEnum
);
