/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import {
  LocationMarkerV2,
  locationMarkerV2Schema,
} from './containers/locationMarkerV2.js';

export interface SingleLocationMarkerResponseV2 {
  /** requestId is unique identifier value that is attached to requests and messages that allow reference to a particular transaction or event chain. */
  requestId?: string;
  /** status of the API call */
  status?: string;
  data?: LocationMarkerV2[];
}

export const singleLocationMarkerResponseV2Schema: Schema<SingleLocationMarkerResponseV2> = lazy(
  () =>
    object({
      requestId: ['requestId', optional(string())],
      status: ['status', optional(string())],
      data: ['data', optional(array(locationMarkerV2Schema))],
    })
);
