/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import {
  ResponseBaseStatusEnum,
  responseBaseStatusEnumSchema,
} from './responseBaseStatusEnum';

export interface SuccessResponse {
  /** A unique request id in GUID format. The value is written to the Shell API Platform audit log for end to end traceability of a request. */
  requestId: string;
  /** Indicates overall status of the request */
  status: ResponseBaseStatusEnum;
}

export const successResponseSchema: Schema<SuccessResponse> = object({
  requestId: ['RequestId', string()],
  status: ['Status', responseBaseStatusEnumSchema],
});
