/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { PriceComponent, priceComponentSchema } from './priceComponent.js';
import { Restrictions, restrictionsSchema } from './restrictions.js';

export interface TariffElement {
  priceComponents: PriceComponent[];
  restrictions?: Restrictions;
}

export const tariffElementSchema: Schema<TariffElement> = lazy(() =>
  object({
    priceComponents: ['priceComponents', array(priceComponentSchema)],
    restrictions: ['restrictions', optional(restrictionsSchema)],
  })
);
