/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TariffVOUpdatedByEnum
 */
export enum TariffVOUpdatedByEnum {
  Feed = 'Feed',
  Admin = 'Admin',
  TariffService = 'TariffService',
  Defaults = 'Defaults',
}

/**
 * Schema for TariffVOUpdatedByEnum
 */
export const tariffVOUpdatedByEnumSchema: Schema<TariffVOUpdatedByEnum> = stringEnum(
  TariffVOUpdatedByEnum
);
