/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  number,
  object,
  Schema,
  string,
} from '../schema.js';
import { PowerRange, powerRangeSchema } from './powerRange.js';
import { TariffAltText, tariffAltTextSchema } from './tariffAltText.js';
import { TariffElement, tariffElementSchema } from './tariffElement.js';
import { TariffTypeEnum, tariffTypeEnumSchema } from './tariffTypeEnum.js';

/** Tariff metadata aligned with TariffV2 GraphQL schema */
export interface TariffV2 {
  /** Unique identifier for the tariff */
  tariffId: string;
  /** Tariff type classification */
  tariffType: TariffTypeEnum;
  powerRange: PowerRange;
  /** Internal identifier used by the platform */
  internalId: string;
  /** Unique identifier of the operator */
  operatorId: string;
  /** Unique identifier of the provider */
  providerId: string;
  /** ISO 4217 Currency Code */
  currency: string;
  tariffAltText: TariffAltText[] | null;
  minPrice: number;
  maxPrice: number;
  elements: TariffElement[];
  startDateTime: string;
  endDateTime: string;
  lastUpdated: string;
  /** Identifier of the actor who created the tariff */
  createdBy: string;
}

export const tariffV2Schema: Schema<TariffV2> = lazy(() =>
  object({
    tariffId: ['tariffId', string()],
    tariffType: ['tariffType', tariffTypeEnumSchema],
    powerRange: ['powerRange', powerRangeSchema],
    internalId: ['internalId', string()],
    operatorId: ['operatorId', string()],
    providerId: ['providerId', string()],
    currency: ['currency', string()],
    tariffAltText: ['tariffAltText', nullable(array(tariffAltTextSchema))],
    minPrice: ['minPrice', number()],
    maxPrice: ['maxPrice', number()],
    elements: ['elements', array(tariffElementSchema)],
    startDateTime: ['startDateTime', string()],
    endDateTime: ['endDateTime', string()],
    lastUpdated: ['lastUpdated', string()],
    createdBy: ['createdBy', string()],
  })
);
