/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TariffTypeEnum
 */
export enum TariffTypeEnum {
  DRIVER = 'DRIVER',
  ROAMING = 'ROAMING',
  REIMBURSEMENT = 'REIMBURSEMENT',
  VMSP = 'VMSP',
}

/**
 * Schema for TariffTypeEnum
 */
export const tariffTypeEnumSchema: Schema<TariffTypeEnum> = stringEnum(
  TariffTypeEnum
);
