/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface TariffAltText {
  /** ISO language code */
  language: string;
  /** Human readable tariff description */
  text: string;
}

export const tariffAltTextSchema: Schema<TariffAltText> = object({
  language: ['language', string()],
  text: ['text', string()],
});
