/**
 * Shell EVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TypeEnum
 */
export enum TypeEnum {
  TIME = 'TIME',
  ENERGY = 'ENERGY',
  FLAT = 'FLAT',
  PARKINGTIME = 'PARKING_TIME',
}

/**
 * Schema for TypeEnum
 */
export const typeEnumSchema: Schema<TypeEnum> = stringEnum(TypeEnum);
